version: 2

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get update
            apt-get --assume-yes install gcc
            apt-get --assume-yes install make
      - run:
          name: Test
          command: make test
