version: 2

dependencies:
  pre:
    -
    - sudo apt-get install gcc
    - sudo apt-get install make

jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get --assume-yes install gcc
            sudo apt-get --assume-yes install make
      - run:
          name: Test
          command: make test
